= Domain Driven Design

== Domain Model

Focus on defining the domain of the problem::
Work with Domain experts on the definition and creating a Ubiquitous language

* Core domain - Unique business model (Twitter - tweet, Youtube - videos)
* Support subdomain - Support core (Comments, Reviews)
* Generic subdomain - Login, User

== Bounded Context / Ubiquitous Language

Words mean different things in different contexts

[mermaid]
----
flowchart TB
    subgraph Concrete
    cset[set]
    cpour[pour]
    cbreak[break]
    end

    subgraph Restaurant
    rset[set]
    rpour[serve]
    rbreak[pour]
    end

    subgraph Tennis
    tset[set]
    tpour[serve]
    tbreak[break]
    end
----


== Entity

An entity is something that is uniquely identifiable and stateful

You might change parts of your car but it's still the same car.

IMPORTANT: Another model of the same car might make the same modifications but 
the two cars are still unique from one another by the license plate (Identifier).

[mermaid]
----
flowchart TB
    subgraph BU66 ETY
    tyres[Change Tyres] -->
    paint[Paint it orange] --> 
    brakes[Change brake pads]
    end
----


== Value

I need $10 I don't care which you give me, $10 is $10. (Immutable)

[mermaid]
----
flowchart TB
    m1[$10]
    m2[$10]
    m3[$10]
----

NOTE: If I was collecting $10 notes and I wanted the serial numbers to be 
in sequential order then the notes would then be treated as Entities by their
serial number

== Aggregate Root

* Contains Entities and Values
* Acts as a Unit of Work for transactions
* Invariant's - Rules that must always be consistent
* Ensure Aggregate is always in a consistent state
* Changes to aggregate is done via the Root (Enforce invariants)


=== Aggregate consistency

Everything in aggregate should be valid. 
No invariants.
Everything is updated as a transaction

.Reservation should only have 2 guests in total.
[mermaid]
----
flowchart LR
    subgraph reservation[Reservation Aggregate]
			root[Reservation] 
			root --> guests
			guests --> Alice
			guests --> Bob
			root --> time
			root --> host
    end
    request[Add guest] -->|Rejected| root
----

=== Reference by Id

* Aggregates can't reach in and change other aggregates

.Aggregates only hold id to aggregate
[mermaid]
----
flowchart TD
    subgraph product[Product Aggregate]
			Product --> Id
    end
    subgraph cart[Cart Aggregate]
			Cart --> CartProductId["ProductId"]
    end
    subgraph warehouse[Warehouse Aggregate]
			Warehouse --> WarehouseProductId["ProductId"]
			Warehouse --> Stock
    end
    subgraph marketing[Marketing Aggregate]
			Marketing --> MarketingProductId["ProductId"]
			Marketing --> Description
    end
----

=== Eventual consistency


.Aggregates only hold id to aggregate
[mermaid]
----
flowchart TD
    subgraph cart[Cart Aggregate]
			Cart --> CartProductId["ProductId"]
    end
    subgraph warehouse[Warehouse Aggregate]
			Warehouse --> WarehouseProductId["ProductId"]
			Warehouse --> Stock
    end
		cart --> ProductAddedToCart:::someclass --> warehouse
		classDef someclass fill:#f96
----
