= Functional

* Prefers Pure function
** No dependency on state or Update state
* Immutability
** Prevent side effects
* Higher Order Functions
** Reduces amount of code which means less bugs 

== Benefits

=== Easier to reason about
As pure functions are self isolated and don't change the world you don't have to worry about calling them.
Whereas with impure functions you have to think how it effects the world, or inconsistent results when calling the function. 

=== Cleaner code

> The Clojure version is shorter. But even more important, it’s simpler: it has no variables, no mutable state, and no branches. This is possible thanks to higher-order functions - (Miller, Halloway and Bedra, 2018)

.Java
[source,java]
----
public class StringUtils {
	public static boolean isBlank(final CharSequence str) {
		int strLen;
		if (str == null || (strLen = str.length()) == 0) {
			return true; 
		}

		for (int i = 0; i < strLen; i++) {
			if (Character.isWhitespace(str.charAt(i)) == false) {
				return false; 
				}
		}

		return true; 
	}
}
----
.Clojure
[source, clojure]
----
(defn blank? [str]
	(every? #(Character/isWhitespace %) str))
----

== Object Orientated fallacy
Polymorphism, Inheritance, and Encapsulation (PIE) is the main selling points of OOP but they don't quite hold up.

=== Polymorphism
Awesome! But not unique to OOP. 
Clojure has Protocols and Multimethods.

=== Inheritance (Prefer composition of inheritance)
If a new type doesn't fit your inheritance hierarchy perfectly then you either have to create a whole new hierarchy or live with the unnecessary extra. Whereas with composition you can just pick and choose what functionality you want.

> The problem with object-oriented languages is they’ve got all this implicit environment that they carry around with them. You wanted a banana but what you got was a gorilla holding the banana and the entire jungle. - Joe Armstrong

=== Encapsulation (Data hiding)
* State is broken up across application (PLOP) have to be concerned about how calling that methods effects the world. (Use immutability instead)
* https://www.youtube.com/watch?v=QM1iUe6IofM&ab_channel=BrianWill[Object-Oriented Programming is Bad]


== References
Miller, A., Halloway, S. and Bedra, A., 2018. 
https://pragprog.com/titles/shcloj3/programming-clojure-third-edition/[Programming Clojure. 3rd ed.]