= Immutability

Main issues with mutable data is the inconsistency/unpredictability. 
Mutation hides change, which create (unexpected) side effects, which can cause nasty bugs. When you enforce immutability you can keep your application architecture and mental model simple, which makes it easier to reason about your application.

== Consistency

|===
| |Data |Pure |Impure

| Consistency 
| Transparent (Predictable)
| Opaque + Predictable results
| Opaque + Unpredictable result 

| Consistency 
a| 
- Viewed many = same result 
a| 
- Called many = same result
- When called = same result

But we don't know the result until we call it, can only make prediction unless we read code.
a| 
- Called many = Maybe different results
- When called = Maybe different result

So we have to be aware of how many times the impure function as been called and when it's been called. But we won't know the result even if we read the code as we won't know what state the function is in.

| Examples
| 1 => 1
| f(1) => 1

f(1) => 1

**(After being called multiple time on many threads)**

f(1) => 1
| f(1) => 1

f(1) => 2

**(After being called multiple time on many threads)**

f(1) => ?

| References
3+a| 
- https://www.youtube.com/watch?v=zznwKCifC1A&ab_channel=ClojureDays[Transparency through data by James Reeves]
|===

== Deterministic

.Python - Impure
[source, python]
----
x = 1
process(x)
print(x) #=> ? (We don't know, need to read how 'process' works)
----

.Python - Pure
[source, python]
----
x = 1
y = process(x)
print(x) #=> 1
print(y) #=> ? (We don't know but at least 'x' not changed) 
----

== Concurrency

Mutable state breaks ACI(D).

* Consistency
** Two threads could read state at the same time, so one update will be lost or process could be applied multiple times even though we only want it run once. (Reference cell problem)
* Isolation
** One thread could be mutating the state while another is reading it.