= Seq

> "Sequences are the key abstraction that connects two of the most important parts of Clojure - immutable persistent collections and the sequence library." - Alex Miller

> "It is better to have 100 functions operate on one data structure than to have 10 functions operate on 10 data structures." - Alan Perlis

NOTE: `seq` is that one data structure

Lisp's core library only worked on lists because everything was a list. 
However Clojure created the `Sequence` abstraction so the same core library could operate on many data structures (list, vector, set, hashmap), focusing on what we can do with the data structure and ignoring the implementation.

.Racket
[source, racket]
----
(first (list 1 2 3)) # => works 
(first (vector 1 2 3))

#|
first: contract violation
  expected: (and/c list? (not/c empty?))
  given: '#(1 2 3)
|#
----

.Clojure
[source, clojure]
----
(first (list 1 2 3)) ; => 1
(first (vector 1 2 3)) ; => 1
----

Data structures::
* list = '()
* vector = []
* set = #{}
* map = {}

So the `Seq` abstraction let you use most of the clojure.core library such as `(first rest reduce sort reverse ...)` on all the different data structures. For example.

[source, clojure]
----
(count '(1 2 3)) => 3
(count [1 2 3]) => 3
(count #{1 2 3}) => 3
(count {:a 1 :b 2 :c 3}) => 3
----

== Implementation

[source, clojure]
----
(defprotocol ISeq
  "Persistent functional Sequence interface"
  (first [_] "get first item in sequence")
  (rest [_] "get rest of sequence")
  (cons [_ x] "add item to sequence")) 
----

== Notes
* Vectors and Maps are not sequences but they are seqable, meaning that they can be converted to sequences.
* Collection that can be viewed as `seqs` are `seq-able` 