= HATEOS

== Glossary

HATEOS::
Hypermedia as the Engine of Application State

== Richardson Maturity Model

|===
| Level | Description

| 0 | Single RPC
| 1 | Categorised RPC endpoints
| 2 | CRUD and status codes
| 3 |

| Level 0
|===

=== Level 0

Single endpoint used for both Create and Read

[cols="1,2,2"]
|===
| Name | Request | Response

| Read appointments
a|
[source,http request]
----
POST /appointmentService
Content-Type: application/json

{
  "date": "2010-01-04",
  "doctor": "mjones"
}
----
a|
[source,http request]
----
200 OK

[{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
},
{
  "start": "16:00",
  "end": "16:50",
  "doctor": "mjones"
}]
----

| Create appointments
a|
[source,http request]
----
POST /appointmentService
Content-Type: application/json

{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones",
  "patient": "alice"
}
----

a|
[source,http request]
----
200 OK

{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones",
  "patient": "alice"
}

OR

200 OK

{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones",
  "patient": "alice",
  "error": "Slot not available"
}

----
|===

=== Level 1

* Adds resources (e.g. `/slot/{id}`, `doctor/{id}/appointments` )

[cols="1,2,2"]
|===
| Name | Request | Response

| Get appointments
a|
[source,http request]
----
POST /doctor/mjones
Content-Type: application/json

{
  "date": "2010-01-04",
}
----
a|
[source,http request]
----
200 OK

[{
  "id": 1234
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
},
{
  "id": 5678
  "start": "16:00",
  "end": "16:50",
  "doctor": "mjones"
}]
----

| Set appointments
a|
[source,http request]
----
POST /slot/1234
Content-Type: application/json

{
  "patient": "alice"
}
----

a|
[source,http request]
----
200 OK

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
  "patient": "alice"
}

----
|===

=== Level 2

.HTTP Verbs
|===
| Verb | Description | Examples

| GET | Read a| `GET /user/123`
| POST | Create a| `POST /user/ {"name": "alice"}`
| PUT | Update a| `PUT /user/alice {"name": "alice wonderland"}`
| DELETE | Delete a| `DELETE /user/alice`
|===

.Status codes
|===
| Code | Description | Examples

| 1xx
| Information
|

| 2xx
| Success
a|
* 200 - Ok
* 201 - Created

| 3xx
| Redirection
a|
* 301 - Redirect
* 304 - Not modified

| 4xx
| Redirection
a|
* 401 - Unauthorised
* 403 - Forbidden
* 404 - Not found
* 405 - Method not allowed

| 5xx
| Server error
a|
* 501 - Not implemented
* 502 - Bad gateway
* 503 - Service unavailable
* 504 - Gateway timeout
|===

[cols="1,2,2"]
|===
| Name | Request | Response

| Get appointments
a|
[source,http request]
----
GET /doctor/mjones/slots?date=2010-01-04
Content-Type: application/json
----

a|
[source,http request]
----
200 OK

[{
  "id": 1234
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
},
{
  "id": 5678
  "start": "16:00",
  "end": "16:50",
  "doctor": "mjones"
}]
----

| Set appointments a|
[source,http request]
----
POST /slot/1234
Content-Type: application/json

{
  "patient": "alice"
}
----

a|
[source,http request]
----
201 Created
Location: slots/1234/appointment

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
  "patient": "alice"
}

OR

409 Conflict

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
}

----
|===

=== Level 3 - HATOES

Hypertext As The Engine Of Application State (HATEOS)

* Links provide indirection for URLs so that URL can be changed without breaking structure
* Links tell you what you can do

.HTTP Verbs
|===
| Verb | Description | Examples

| GET | Read a| `GET /user/123`
| POST | Create a| `POST /user/ {"name": "alice"}`
| PUT | Update a| `PUT /user/alice {"name": "alice wonderland"}`
| DELETE | Delete a| `DELETE /user/alice`
|===

[cols="1,2,2"]
|===
| Name | Request | Response

| Get appointments
a|
[source,http request]
----
GET /doctor/mjones/slots?date=2010-01-04
Content-Type: application/json
----

a|
[source,http request]
----
200 OK

[
    {
      "id": 1234
      "start": "14:00",
      "end": "14:50",
      "doctor": "mjones",
      "_links": {
        "rel": "/slots/1234",
        "book": "/slots/book"
      }
    },
    {
      "id": 5678
      "start": "16:00",
      "end": "16:50",
      "doctor": "mjones",
      "_links": {
        "rel": "/slots/1234",
        "book": "/slots/book"
      }
    }
]
----

| Set appointments a|
[source,http request]
----
POST /slot/1234
Content-Type: application/json

{
  "patient": "alice"
}
----

a|
[source,http request]
----
201 Created
Location: slots/1234/appointment

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
  "patient": "alice",
  "_links": {
    "self": "/slots/1234",
    "delete": "/slots/1234",
    "update": "/slots/1234",
  }
}

----

|===