= Representational state transfer (REST)

== Glossary

HATEOS::
Hypermedia as the Engine of Application State

== Richardson Maturity Model

|===
| Level | Description

| 0 | Single RPC
| 1 | Categorised RPC endpoints
| 2 | CRUD and status codes
| 3 | Level 2 + Internal navigation + List what you can do
|===

=== Level 0

Single endpoint used for both Create and Read

[cols="1,2,2"]
|===
| Name | Request | Response

| Read appointments
a|
[source,http request]
----
POST /appointmentService
Content-Type: application/json

{
  "date": "2010-01-04",
  "doctor": "mjones"
}
----
a|
[source,http request]
----
200 OK

[{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
},
{
  "start": "16:00",
  "end": "16:50",
  "doctor": "mjones"
}]
----

| Create appointments
a|
[source,http request]
----
POST /appointmentService
Content-Type: application/json

{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones",
  "patient": "alice"
}
----

a|
[source,http request]
----
200 OK

{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones",
  "patient": "alice"
}

OR

200 OK

{
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones",
  "patient": "alice",
  "error": "Slot not available"
}

----
|===

=== Level 1

* Adds resources (e.g. `/slot/{id}`, `doctor/{id}/appointments` )

[cols="1,2,2"]
|===
| Name | Request | Response

| Get appointments
a|
[source,http request]
----
POST /doctor/mjones
Content-Type: application/json

{
  "date": "2010-01-04",
}
----
a|
[source,http request]
----
200 OK

[{
  "id": 1234
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
},
{
  "id": 5678
  "start": "16:00",
  "end": "16:50",
  "doctor": "mjones"
}]
----

| Set appointments
a|
[source,http request]
----
POST /slot/1234
Content-Type: application/json

{
  "patient": "alice"
}
----

a|
[source,http request]
----
200 OK

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
  "patient": "alice"
}

----
|===

=== Level 2

[cols="1,1,4"]
.HTTP Verbs
|===
| Verb | Description | Examples

| GET | Read
a|
[source,http request]
----
GET /user/123
----

| POST | Create
a|
[source,http request]
----
POST /user/
{"id": 123, "name": "alice", "age": 20}
----

| PUT | Update entity
a|
[source,http request]
----
PUT /user/123
{"id": 123, "name": "alice wonderland", "age": 20}
----

| PATCH | Update property
a|
[source,http request]
----
PATCH /user/123
{"name": "alice wonderland"}`
----

| DELETE | Delete
a|
[source,http request]
----
DELETE /user/123`
----
|===

.Status codes
[cols="1,1,2"]
|===
| Code | Description | Examples

| 1xx
| Information
|

| 2xx
| Success
a|
* 200 - Ok
* 201 - Created

| 3xx
| Redirection
a|
* 301 - Redirect
* 304 - Not modified

| 4xx
| Redirection
a|
* 401 - Unauthorised
* 403 - Forbidden
* 404 - Not found
* 405 - Method not allowed

| 5xx
| Server error
a|
* 501 - Not implemented
* 502 - Bad gateway
* 503 - Service unavailable
* 504 - Gateway timeout
|===

[cols="1,3,2"]
|===
| Name | Request | Response

| Get appointments
a|
[source,http request]
----
GET /doctor/mjones/slots?date=2010-01-04
Content-Type: application/json
----

a|
[source,http request]
----
200 OK

[{
  "id": 1234
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
},
{
  "id": 5678
  "start": "16:00",
  "end": "16:50",
  "doctor": "mjones"
}]
----

| Set appointments a|
[source,http request]
----
POST /slot/1234
Content-Type: application/json

{
  "patient": "alice"
}
----

a|
[source,http request]
----
201 Created
Location: slots/1234/appointment

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
  "patient": "alice"
}

OR

409 Conflict

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
}

----
|===

=== Level 3 - HATOES

Hypertext As The Engine Of Application State (HATEOS)

* Links provide
** Location transparency
*** Creates internal navigation so that external links can changed without breaking changes.
(Indirection)
** Links to what you can do next

[cols="1,2,4"]
|===
| Name | Request | Response

| Discovery
a|
[source,http request]
----
GET /
----
a|
[source,http request]
----
200 OK

{
    "_links": {
        "self": "https://website.com",
        "discovery": "https://website.com",
        "health": "https://website.com/health",
        "slots": "https://slots-service.com/slots",
        "doctors": "https://doctor-service.com/",
        "schedule": "https://website.com/schedule",
    }
}
----

| Get appointments
a|
[source,http request]
----
GET /doctor/mjones/slots?date=2010-01-04
Content-Type: application/json
----

a|
[source,http request]
----
200 OK

{
      "_links": {
        "self": "/slots"
      },
     "slots": [
        {
          "id": 1234
          "start": "14:00",
          "end": "14:50",
          "doctor": "mjones"
        },
        {
          "id": 5678
          "start": "16:00",
          "end": "16:50",
          "doctor": "mjones",
        }
    ]
}
----

| Set appointments a|
[source,http request]
----
POST /slot/1234
Content-Type: application/json

{
  "patient": "alice"
}
----

a|
[source,http request]
----
201 Created
Location: slots/1234/appointment

{
  "id": 1234,
  "start": "14:00",
  "end": "14:50",
  "doctor": "mjones"
  "patient": "alice",
  "_links": {
    "self": "/slots/1234",
    "delete": "/slots/1234",
    "update": "/slots/1234",
  }
}

----

|===